(() => {
  const rows = [
    ["Kostenloses Angebot innerhalb von", "Бесплатна понуда во рок од", "Ofertë falas brenda"],
    ["Antwort in 8 Stunden · kostenlos & unverbindlich", "Одговор во рок од 8 часа · бесплатно и без обврска", "Përgjigje brenda 8 orësh · falas dhe pa detyrim"],
    ["Regensburg & Umgebung", "Регенсбург и околината", "Regensburg dhe rrethina"],
    ["Sprache wählen", "Изберете јазик", "Zgjidhni gjuhën"],
    ["PROHAUS Startseite", "Почетна страница на PROHAUS", "Faqja kryesore e PROHAUS"],
    ["Fenster & Türen", "Прозорци и врати", "Dritare dhe dyer"],
    ["ohne komplizierte Wege.", "без комплицирани постапки.", "pa procedura të ndërlikuara."],
    ["MONTAGE & SERVICE", "МОНТАЖА И СЕРВИС", "MONTIM DHE SHËRBIM"],
    ["Projekt anfragen", "Побарајте понуда", "Kërkoni ofertë"],
    ["Leistungen", "Услуги", "Shërbimet"],
    ["Reparatur", "Поправка", "Riparim"],
    ["So einfach geht es", "Толку е едноставно", "Kaq e thjeshtë është"],
    ["Projekte", "Проекти", "Projektet"],
    ["Kontakt", "Контакт", "Kontakti"],
    ["MONTAGE & KOMPLETTLÖSUNGEN IN REGENSBURG", "МОНТАЖА И ЦЕЛОСНИ РЕШЕНИЈА ВО РЕГЕНСБУРГ", "MONTIM DHE ZGJIDHJE TË PLOTA NË REGENSBURG"],
    ["Kostenloses Angebot innerhalb von 8 Stunden.", "Бесплатна понуда во рок од 8 часа.", "Ofertë falas brenda 8 orësh."],
    ["Fenster", "Прозорци", "Dritare"],
    ["Türen", "Врати", "Dyer"],
    ["Dachfenster", "Кровни прозорци", "Dritare çatie"],
    ["Rollläden & Jalousien", "Ролетни и жалузини", "Grila dhe persiana"],
    ["Markisen", "Тенди", "Tenda"],
    ["Von der Anfrage bis zur professionellen Montage – alles aus einer Hand.", "Од првото барање до професионалната монтажа – сè на едно место.", "Nga kërkesa deri te montimi profesional – gjithçka në një vend."],
    ["Kostenloses Angebot anfordern", "Побарајте бесплатна понуда", "Kërkoni ofertë falas"],
    ["Unsere Leistungen", "Нашите услуги", "Shërbimet tona"],
    ["Schreiben Sie uns per WhatsApp oder senden Sie uns eine E-Mail –", "Пишете ни на WhatsApp или испратете ни е-пошта –", "Na shkruani në WhatsApp ose na dërgoni email –"],
    ["wir kontaktieren Sie schnellstmöglich.", "ќе ве контактираме што е можно побрзо.", "do t'ju kontaktojmë sa më shpejt."],
    ["WhatsApp", "WhatsApp", "WhatsApp"], ["E-Mail", "Е-пошта", "Email"],
    ["Persönlich. Sorgfältig. Aus einer Hand.", "Лично. Внимателно. Сè на едно место.", "Personalizuar. Me kujdes. Gjithçka në një vend."],
    ["Beratung, Aufmaß und fachgerechte Montage", "Советување, мерење и стручна монтажа", "Këshillim, matje dhe montim profesional"],
    ["Alles aus einer Hand", "Сè на едно место", "Gjithçka në një vend"],
    ["Von der Beratung bis zur Montage", "Од советување до монтажа", "Nga këshillimi deri te montimi"],
    ["Aufmaß vor Ort", "Мерење на лице место", "Matje në vend"],
    ["Wir kümmern uns um die Maße", "Ние се грижиме за мерењето", "Ne kujdesemi për matjet"],
    ["Persönlich vor Ort für Sie da", "Ви стоиме на располагање лично на терен", "Jemi pranë jush personalisht"],
    ["WAS WIR FÜR SIE TUN", "ШТО МОЖЕМЕ ДА НАПРАВИМЕ ЗА ВАС", "ÇFARË BËJMË PËR JU"],
    ["Ein Zuhause. Viele Möglichkeiten.", "Еден дом. Многу можности.", "Një shtëpi. Shumë mundësi."],
    ["Wir kümmern uns um die Arbeit, die Ihr Zuhause besser macht – sorgfältig geplant und professionell umgesetzt.", "Се грижиме за работите што го подобруваат вашиот дом – внимателно испланирани и професионално изведени.", "Kujdesemi për punët që e përmirësojnë shtëpinë tuaj – të planifikuara me kujdes dhe të realizuara profesionalisht."],
    ["01 / FENSTER & TÜREN", "01 / ПРОЗОРЦИ И ВРАТИ", "01 / DRITARE DHE DYER"],
    ["Passende Lösungen.", "Решенија по ваша мерка.", "Zgjidhje të përshtatshme."],
    ["Sauber eingebaut.", "Уредно монтирани.", "Të montuara me kujdes."],
    ["Fenster & Türen nach Ihren Anforderungen. Wir beraten Sie bei der Auswahl und bieten passende Fenster- und Türlösungen inklusive professioneller Montage.", "Прозорци и врати според вашите потреби. Ве советуваме при изборот и нудиме соодветни решенија со професионална монтажа.", "Dritare dhe dyer sipas kërkesave tuaja. Ju këshillojmë në zgjedhje dhe ofrojmë zgjidhje të përshtatshme me montim profesional."],
    ["Leistung anfragen", "Побарајте услуга", "Kërkoni shërbimin"],
    ["02 / ROLLLÄDEN & JALOUSIEN", "02 / РОЛЕТНИ И ЖАЛУЗИНИ", "02 / GRILA DHE PERSIANA"],
    ["Beschattung.", "Засенчување.", "Mbrojtje nga dielli."],
    ["Fachgerecht montiert.", "Стручно монтирано.", "Montim profesional."],
    ["Wir übernehmen die Montage von Rollläden und Jalousien, passend zu Ihren Fenstern und Ihrem Zuhause.", "Монтираме ролетни и жалузини што одговараат на вашите прозорци и дом.", "Montojmë grila dhe persiana që përshtaten me dritaret dhe shtëpinë tuaj."],
    ["Montage anfragen", "Побарајте монтажа", "Kërkoni montim"],
    ["03 / MONTAGE & SERVICE", "03 / МОНТАЖА И СЕРВИС", "03 / MONTIM DHE SHËRBIM"],
    ["Das ganze Projekt.", "Целиот проект.", "I gjithë projekti."],
    ["In guten Händen.", "Во сигурни раце.", "Në duar të sigurta."],
    ["Demontage, Abdichtung und passendes Zubehör – wir kümmern uns um die Details bis zum sauberen Abschluss.", "Демонтажа, заптивање и соодветна опрема – се грижиме за деталите до уредното завршување.", "Çmontim, izolim dhe pajisje të përshtatshme – kujdesemi për çdo detaj deri në përfundimin e pastër."],
    ["REPARATUR & INSTANDHALTUNG", "ПОПРАВКА И ОДРЖУВАЊЕ", "RIPARIM DHE MIRËMBAJTJE"],
    ["SERVICE, DER WEITERHILFT", "УСЛУГА ШТО ПОМАГА", "SHËRBIM QË JU NDIHMON"],
    ["Fenster, Türen oder Rollläden machen Probleme?", "Имате проблем со прозорци, врати или ролетни?", "Keni problem me dritaret, dyert ose grilat?"],
    ["Wir unterstützen Sie auch bei Reparaturen rund ums Haus. Sprechen Sie uns an – wir schauen uns an, was nicht richtig funktioniert, und besprechen die passende Lösung.", "Ви помагаме и со поправки низ домот. Јавете ни се – ќе провериме што не функционира и ќе разговараме за соодветно решение.", "Ju ndihmojmë edhe me riparime në shtëpi. Na kontaktoni – shohim çfarë nuk funksionon dhe diskutojmë zgjidhjen e duhur."],
    ["Reparatur von Fenstern", "Поправка на прозорци", "Riparim i dritareve"],
    ["Reparatur von Türen", "Поправка на врати", "Riparim i dyerve"],
    ["Reparatur von Rollläden", "Поправка на ролетни", "Riparim i grilave"],
    ["Reparaturanfrage senden", "Испратете барање за поправка", "Dërgoni kërkesë për riparim"],
    ["KLARER ABLAUF, GUTES GEFÜHL", "ЈАСЕН ТЕК НА РАБОТА, ДОБРО ЧУВСТВО", "PROCES I QARTË, QETËSI MENDORE"],
    ["So einfach", "Толку е едноставно", "Kaq e thjeshtë"],
    ["geht es.", "оди процесот.", "është procesi."],
    ["Sie sagen uns, was Sie vorhaben. Wir begleiten Sie Schritt für Schritt bis zur fertigen Montage.", "Кажете ни што планирате. Ве водиме чекор по чекор до завршената монтажа.", "Na tregoni çfarë planifikoni. Ju udhëheqim hap pas hapi deri në montimin përfundimtar."],
    ["Jetzt Projekt starten", "Започнете проект", "Nisni projektin"],
    ["Anfrage senden", "Испратете барање", "Dërgoni kërkesë"],
    ["Per WhatsApp, E-Mail oder telefonisch.", "Преку WhatsApp, е-пошта или телефон.", "Me WhatsApp, email ose telefon."],
    ["Beratung & Aufmaß", "Советување и мерење", "Këshillim dhe matje"],
    ["Wir besprechen Ihr Projekt und nehmen die notwendigen Maße vor Ort.", "Го разгледуваме вашиот проект и ги земаме потребните мерки на лице место.", "Diskutojmë projektin tuaj dhe marrim matjet e nevojshme në vend."],
    ["Kostenloses Angebot innerhalb von 8 Stunden", "Бесплатна понуда во рок од 8 часа", "Ofertë falas brenda 8 orësh"],
    ["Sie erhalten ein kostenloses und transparentes Angebot.", "Добивате бесплатна и транспарентна понуда.", "Merrni një ofertë falas dhe transparente."],
    ["Montage", "Монтажа", "Montim"],
    ["Wir kümmern uns um die professionelle Montage.", "Се грижиме за професионалната монтажа.", "Kujdesemi për montimin profesional."],
    ["VON ANFANG BIS ABSCHLUSS", "ОД ПОЧЕТОК ДО КРАЈ", "NGA FILLIMI DERI NË PËRFUNDIM"],
    ["Wir überlassen nichts", "Не препуштаме ништо", "Nuk lëmë asgjë"],
    ["dem Zufall.", "на случајноста.", "rastësisë."],
    ["Demontage, sorgfältige Abdichtung und das passende Zubehör: Wir kümmern uns um alle Schritte, damit am Ende alles zusammenpasst.", "Демонтажа, внимателно заптивање и соодветна опрема: се грижиме за секој чекор за сè да се вклопи на крајот.", "Çmontim, izolim i kujdesshëm dhe pajisje të përshtatshme: kujdesemi për çdo hap që gjithçka të përputhet në fund."],
    ["Projekt anfragen", "Побарајте проект", "Kërkoni projekt"],
    ["EINBLICKE IN UNSERE ARBEIT", "ПОГЛЕД ВО НАШАТА РАБОТА", "NJË VËSHTRIM NË PUNËN TONË"],
    ["Unsere Projekte.", "Нашите проекти.", "Projektet tona."],
    ["Einblicke in Fenster- und Türlösungen, Dachfenster, Beschattung und die Arbeit vor Ort.", "Погледнете решенија за прозорци и врати, кровни прозорци, засенчување и работа на терен.", "Shikoni zgjidhje për dritare e dyer, dritare çatie, mbrojtje nga dielli dhe punë në terren."],
    ["FENSTERFRONT", "ПРОЗОРСКА ФРОНТАЛА", "FASADË ME DRITARE"], ["Großzügige Glasflächen", "Големи стаклени површини", "Sipërfaqe të mëdha xhami"],
    ["FENSTER & TÜREN", "ПРОЗОРЦИ И ВРАТИ", "DRITARE DHE DYER"], ["Schiebetür in Anthrazit", "Лизгачка врата во антрацит", "Derë rrëshqitëse antracit"],
    ["FENSTER & BESCHATTUNG", "ПРОЗОРЦИ И ЗАСЕНЧУВАЊЕ", "DRITARE DHE MBROJTJE NGA DIELLI"], ["Balkonfront mit Rollläden", "Балконска фронта со ролетни", "Ballkon me grila"],
    ["FENSTER", "ПРОЗОРЦИ", "DRITARE"], ["Schiebefenster", "Лизгачки прозорец", "Dritare rrëshqitëse"],
    ["FENSTER & ROLLLÄDEN", "ПРОЗОРЦИ И РОЛЕТНИ", "DRITARE DHE GRILA"], ["Beschattung am Gebäude", "Засенчување на објектот", "Mbrojtje nga dielli në fasadë"],
    ["MONTAGE", "МОНТАЖА", "MONTIM"], ["Vorbereitung am Fenster", "Подготовка на прозорецот", "Përgatitja e dritares"],
    ["FENSTER & ROLLLADEN", "ПРОЗОРЕЦ И РОЛЕТНА", "DRITARE DHE GRILË"], ["Fenster mit Rollladen", "Прозорец со ролетна", "Dritare me grilë"],
    ["MONTAGEDETAILS", "ДЕТАЛИ ОД МОНТАЖАТА", "DETAJE MONTIMI"], ["Präzise Arbeitsschritte", "Прецизни работни чекори", "Hapa pune të saktë"],
    ["Fensterfront im Innenraum", "Прозорска фронта во ентериер", "Fasadë me dritare në ambient të brendshëm"],
    ["HAUSTÜR", "ВЛЕЗНА ВРАТА", "DERË HYRËSE"], ["Heller Eingangsbereich", "Светол влезен простор", "Hyrje e ndriçuar"],
    ["Moderne Haustür", "Модерна влезна врата", "Derë hyrëse moderne"], ["Klare Linien am Eingang", "Чисти линии на влезот", "Vija të pastra në hyrje"],
    ["Anthrazit und Holzoptik", "Антрацит и изглед на дрво", "Antracit dhe pamje druri"],
    ["FENSTERPROFIL", "ПРОЗОРСКИ ПРОФИЛ", "PROFIL DRITAREJE"], ["Profilaufbau im Detail", "Детален приказ на профилот", "Profili në detaje"], ["Rahmen und Verglasung", "Рамка и застаклување", "Korniza dhe xhami"],
    ["DACHFENSTER", "КРОВЕН ПРОЗОРЕЦ", "DRITARE ÇATIE"], ["Licht unterm Dach", "Светлина под покривот", "Dritë nën çati"], ["Geöffnetes Dachfenster in einem Ziegeldach", "Отворен кровен прозорец на покрив од ќерамиди", "Dritare çatie e hapur në çati me tjegulla"], ["Dachfenster im Ziegeldach", "Кровен прозорец на покрив од ќерамиди", "Dritare çatie në çati me tjegulla"], ["Innenansicht mit Sonnenschutz", "Внатрешен поглед со заштита од сонце", "Pamje e brendshme me mbrojtje nga dielli"],
    ["ROLLLÄDEN", "РОЛЕТНИ", "GRILA"], ["Außenliegende Beschattung", "Надворешно засенчување", "Mbrojtje e jashtme nga dielli"], ["Beschattung am Wohnbereich", "Засенчување на дневниот простор", "Mbrojtje nga dielli në ambientin e ndenjjes"], ["Rollladen am Fenster", "Ролетна на прозорец", "Grilë në dritare"],
    ["IHR PROJEKT BEGINNT HIER", "ВАШИОТ ПРОЕКТ ПОЧНУВА ТУКА", "PROJEKTI JUAJ FILLON KËTU"],
    ["Sie planen", "Планирате", "Po planifikoni"], ["ein Projekt?", "проект?", "një projekt?"],
    ["Fordern Sie jetzt Ihr kostenloses Angebot an.", "Побарајте бесплатна понуда уште сега.", "Kërkoni ofertën tuaj falas tani."],
    ["Innerhalb von 8 Stunden", "Во рок од 8 часа", "Brenda 8 orësh"], ["melden wir uns bei Ihnen zurück.", "ќе ви одговориме.", "do t'ju kontaktojmë përsëri."],
    ["Oder schreiben Sie uns direkt per WhatsApp oder E-Mail.", "Или пишете ни директно преку WhatsApp или е-пошта.", "Ose na shkruani drejtpërdrejt në WhatsApp ose email."],
    ["Name", "Име", "Emri"], ["Telefon", "Телефон", "Telefoni"], ["E-Mail", "Е-пошта", "Email"], ["Ort", "Место", "Qyteti"],
    ["Was benötigen Sie?", "Што ви е потребно?", "Çfarë ju nevojitet?"], ["Jalousien", "Жалузини", "Persiana"], ["Sonstiges", "Друго", "Tjetër"], ["Nachricht", "Порака", "Mesazhi"],
    ["Erzählen Sie uns kurz von Ihrem Vorhaben …", "Накратко опишете ни го вашиот проект …", "Na tregoni shkurt për projektin tuaj …"], ["Fotos hochladen", "Прикачете фотографии", "Ngarkoni fotografi"], ["Optional · Bilder Ihres Projekts auswählen", "Изборно · изберете фотографии од вашиот проект", "Opsionale · zgjidhni fotografi të projektit tuaj"], ["Dateien wählen", "Изберете датотеки", "Zgjidhni skedarët"],
    ["Mit dem Klick öffnet sich eine vorbereitete E-Mail. Ihre Fotos können Sie dort anhängen.", "Со кликнување ќе се отвори подготвена е-пошта. Фотографиите можете да ги прикачите таму.", "Me klikim hapet një email i përgatitur. Fotografitë mund t'i bashkëngjitni aty."],
    ["Montage & Service rund ums Haus", "Монтажа и сервис за домот", "Montim dhe shërbime për shtëpinë"], ["Baufertigteile · Hausmeisterservice", "Градежни елементи · одржување на објекти", "Elemente ndërtimi · mirëmbajtje objektesh"], ["Nach oben", "На врвот", "Në krye"], ["Impressum", "Импресум", "Impressum"], ["Datenschutz", "Заштита на податоци", "Privatësia"], ["Mit Sorgfalt gemacht", "Изработено со внимание", "Punuar me kujdes"],
    ["Menü öffnen", "Отворете го менито", "Hapni menynë"], ["Menü schließen", "Затворете го менито", "Mbyllni menynë"], ["Fenster, Türen und professionelle Montage", "Прозорци, врати и професионална монтажа", "Dritare, dyer dhe montim profesional"],
    ["Kostenloses Angebot innerhalb von 8 Stunden · PROHAUS", "Бесплатна понуда во рок од 8 часа · PROHAUS", "Ofertë falas brenda 8 orësh · PROHAUS"],
    ["PROHAUS – Montage & Service rund ums Haus in Regensburg und Umgebung. Kostenloses Angebot innerhalb von 8 Stunden.", "PROHAUS – монтажа и сервис за домот во Регенсбург и околината. Бесплатна понуда во рок од 8 часа.", "PROHAUS – montim dhe shërbime për shtëpinë në Regensburg dhe rrethinë. Ofertë falas brenda 8 orësh."],
    ["Rechtliche Angaben", "Правни информации", "Të dhëna ligjore"], ["Angaben gemäß § 5 DDG", "Податоци согласно § 5 DDG", "Të dhëna sipas § 5 DDG"], ["Inhaber:", "Сопственик:", "Pronari:"], ["Kontakt", "Контакт", "Kontakti"], ["Telefon:", "Телефон:", "Telefoni:"], ["Steuerliche Angaben", "Даночни информации", "Të dhëna tatimore"], ["Steuernummer:", "Даночен број:", "Numri tatimor:"], ["Umsatzsteuer: Kleinunternehmer gemäß § 19 UStG", "ДДВ: мал претприемач според § 19 UStG", "TVSH: biznes i vogël sipas § 19 UStG"], ["USt-IdNr.: Nicht vorhanden", "Идентификациски број за ДДВ: нема", "Nr. i TVSH-së: nuk ka"], ["Registereintrag", "Регистарски запис", "Regjistrimi në regjistër"], ["Kein Handelsregistereintrag vorhanden.", "Нема упис во трговскиот регистар.", "Nuk ka regjistrim në regjistrin tregtar."], ["Verantwortlich für den Inhalt", "Одговорен за содржината", "Përgjegjës për përmbajtjen"], ["Hinweis zur Streitbeilegung", "Информации за решавање спорови", "Informacion për zgjidhjen e mosmarrëveshjeve"], ["Wir sind nicht verpflichtet und nicht bereit, an Streitbeilegungsverfahren vor einer Verbraucherschlichtungsstelle teilzunehmen.", "Не сме обврзани и не сме подготвени да учествуваме во постапка за решавање спорови пред тело за арбитража на потрошувачи.", "Nuk jemi të detyruar dhe nuk jemi të gatshëm të marrim pjesë në procedurë zgjidhjeje mosmarrëveshjesh pranë një organi arbitrazhi për konsumatorët."], ["←︎ Zurück zu PROHAUS", "←︎ Назад кон PROHAUS", "←︎ Kthehu te PROHAUS"],
    ["Datenschutzerklärung", "Политика за приватност", "Deklarata e privatësisë"], ["DATENSCHUTZ", "ЗАШТИТА НА ПОДАТОЦИ", "PRIVATËSIA"],
    ["1. Verantwortlicher", "1. Одговорно лице", "1. Kontrolluesi"], ["2. Datenschutzbeauftragter", "2. Службеник за заштита на податоци", "2. Zyrtari për mbrojtjen e të dhënave"], ["3. Allgemeine Hinweise", "3. Општи информации", "3. Informacione të përgjithshme"], ["4. Kontaktaufnahme per Formular, E-Mail und WhatsApp", "4. Контакт преку формулар, е-пошта и WhatsApp", "4. Kontakti përmes formularit, emailit dhe WhatsApp"], ["4. Kontaktaufnahme per Formular, E-Mail und WhatsApp", "4. Контакт преку формулар, е-пошта и WhatsApp", "4. Kontakti përmes formularit, emailit dhe WhatsApp"], ["5. Zweck und Rechtsgrundlage der Verarbeitung", "5. Цел и правна основа за обработката", "5. Qëllimi dhe baza ligjore e përpunimit"], ["6. Pflicht zur Bereitstellung der Daten", "6. Обврска за доставување податоци", "6. Detyrimi për dhënien e të dhënave"], ["7. Speicherdauer", "7. Времетраење на чувањето", "7. Kohëzgjatja e ruajtjes"], ["8. Weitergabe an Dritte", "8. Споделување со трети страни", "8. Ndarja me palë të treta"], ["9. Hosting und technische Bereitstellung", "9. Хостирање и техничко обезбедување", "9. Hostimi dhe ofrimi teknik"], ["10. Externe Schriftarten und Bilder", "10. Надворешни фонтови и слики", "10. Shkronja dhe imazhe të jashtme"], ["11. Cookies und lokale Speicherung", "11. Колачиња и локално складирање", "11. Cookies dhe ruajtja lokale"], ["12. Automatisierte Entscheidungsfindung", "12. Автоматизирано донесување одлуки", "12. Vendimmarrja e automatizuar"], ["13. Ihre Rechte", "13. Вашите права", "13. Të drejtat tuaja"], ["14. Beschwerderecht", "14. Право на жалба", "14. E drejta për ankesë"], ["15. Aktualität dieser Datenschutzerklärung", "15. Ажурирање на оваа политика за приватност", "15. Përditësimi i kësaj deklarate të privatësisë"],
    ["Auskunft, Berichtigung, Löschung", "Пристап, исправка, бришење", "Qasje, korrigjim, fshirje"], ["Angaben übernommen von der bisherigen PROHAUS-Website · Stand der Vorlage: Juni 2026", "Податоци преземени од претходната веб-страница на PROHAUS · верзија: јуни 2026", "Të dhënat janë marrë nga faqja e mëparshme e PROHAUS · versioni: qershor 2026"], ["Angaben übernommen und für diese Website angepasst · Stand der Vorlage: Juni 2026", "Податоците се преземени и приспособени за оваа веб-страница · верзија: јуни 2026", "Të dhënat janë marrë dhe përshtatur për këtë faqe · versioni: qershor 2026"],
    ["Ihr Name", "Вашето име", "Emri juaj"], ["Ihre Telefonnummer", "Вашиот телефонски број", "Numri juaj i telefonit"], ["ihre@email.de", "вашата@email.de", "emaili-juaj@email.com"], ["Fenster und Türen nach Ihren Anforderungen", "Прозорци и врати според вашите потреби", "Dritare dhe dyer sipas kërkesave tuaja"], ["Monteur arbeitet an einem Fensterrahmen", "Монтер работи на прозорска рамка", "Montuesi punon në kornizën e dritares"],
    ["Fotos zum Anhängen", "Фотографии за прикачување", "Fotografitë për bashkëngjitje"], ["keine", "нема", "asnjë"], ["Anfrage für ein kostenloses Angebot", "Барање за бесплатна понуда", "Kërkesë për ofertë falas"], ["Kontaktperson", "Контакт лице", "Personi i kontaktit"],
    ["Die Daten werden verarbeitet, um Ihre Anfrage zu beantworten, ein Angebot zu erstellen, Rückfragen zu klären und gegebenenfalls einen Montagetermin zu vereinbaren.", "Податоците се обработуваат за да одговориме на вашето барање, да изготвиме понуда, да разјасниме прашања и, доколку е потребно, да договориме термин за монтажа.", "Të dhënat përpunohen për t'iu përgjigjur kërkesës suaj, për të përgatitur ofertë, për të sqaruar pyetje dhe, nëse nevojitet, për të caktuar termin e montimit."],
    ["Diese Website setzt derzeit keine Analyse- oder Marketing-Cookies und speichert keine Cookie-Einstellungen in Ihrem Browser.", "Оваа веб-страница во моментов не користи колачиња за анализа или маркетинг и не зачувува поставки за колачиња во вашиот прелистувач.", "Kjo faqe aktualisht nuk përdor cookies analitike ose marketingu dhe nuk ruan cilësime cookies në shfletuesin tuaj."],
    ["Datenschutzerklärung | PROHAUS", "Политика за приватност | PROHAUS", "Deklarata e privatësisë | PROHAUS"], ["Impressum | PROHAUS", "Импресум | PROHAUS", "Impressum | PROHAUS"], ["PROHAUS — Montage & Service rund ums Haus", "PROHAUS — монтажа и сервис за домот", "PROHAUS — montim dhe shërbime për shtëpinë"],
    ["4. Kontaktaufnahme per Formular, E-Mail und WhatsApp", "4. Контакт преку формулар, е-пошта и WhatsApp", "4. Kontakti përmes formularit, emailit dhe WhatsApp"],
    ["Verantwortlich für die Datenverarbeitung auf dieser Website ist:", "Одговорно за обработката на податоците на оваа веб-страница е:", "Përgjegjës për përpunimin e të dhënave në këtë faqe është:"],
    ["Ein Datenschutzbeauftragter ist nicht bestellt, da nach aktueller Einschätzung keine gesetzliche Pflicht zur Bestellung eines Datenschutzbeauftragten besteht.", "Не е назначен службеник за заштита на податоци, бидејќи според сегашната проценка нема законска обврска за негово назначување.", "Nuk është caktuar zyrtar për mbrojtjen e të dhënave, pasi sipas vlerësimit aktual nuk ekziston detyrim ligjor për një caktim të tillë."],
    ["Wir behandeln Ihre personenbezogenen Daten vertraulich und entsprechend den gesetzlichen Datenschutzvorschriften. Personenbezogene Daten sind alle Daten, mit denen Sie persönlich identifiziert werden können, zum Beispiel Name, Telefonnummer, Adresse oder Angaben zu einer Anfrage.", "Вашите лични податоци ги третираме доверливо и согласно законските прописи за заштита на податоците. Лични податоци се сите податоци со кои може да бидете идентификувани, на пример име, телефонски број, адреса или информации за барање.", "Të dhënat tuaja personale i trajtojmë në mënyrë konfidenciale dhe në përputhje me ligjet për mbrojtjen e të dhënave. Të dhëna personale janë të gjitha të dhënat me të cilat mund të identifikoheni, si emri, numri i telefonit, adresa ose të dhënat e një kërkese."],
    ["Wenn Sie das Anfrageformular nutzen, werden die von Ihnen eingegebenen Daten verarbeitet. Dazu gehören Name, Telefonnummer, E-Mail-Adresse, Ort, ausgewählte Leistungen und Ihre Nachricht. Das Formular sendet diese Daten nicht an einen eigenen Server. Nach dem Absenden wird Ihr E-Mail-Programm mit einer vorbereiteten Nachricht geöffnet. Die Nachricht wird erst an uns übermittelt, wenn Sie sie selbst in Ihrem E-Mail-Programm absenden. Fotos werden nicht automatisch angefügt; Sie können sie dort selbst anhängen.", "Кога го користите формуларот, ги обработуваме податоците што ги внесувате: име, телефонски број, е-пошта, место, избрани услуги и порака. Формуларот не ги испраќа податоците до наш сервер. По испраќањето се отвора вашата е-пошта со подготвена порака. До нас се испраќа дури откако сами ќе ја испратите од вашата е-пошта. Фотографиите не се прикачуваат автоматски; можете сами да ги прикачите.", "Kur përdorni formularin, përpunojmë të dhënat që vendosni: emrin, numrin e telefonit, emailin, vendbanimin, shërbimet e zgjedhura dhe mesazhin. Formulari nuk i dërgon këto të dhëna në serverin tonë. Pas plotësimit hapet programi juaj i emailit me një mesazh të përgatitur. Mesazhi na dërgohet vetëm pasi ta nisni vetë nga emaili juaj. Fotografitë nuk bashkëngjiten automatikisht; mund t'i bashkëngjitni vetë."],
    ["Wenn Sie uns über den WhatsApp-Link kontaktieren, wird WhatsApp mit einer vorbereiteten Nachricht geöffnet. Die Nachricht wird erst über WhatsApp versendet, wenn Sie diese dort selbst absenden.", "Ако нè контактирате преку WhatsApp-врската, WhatsApp ќе се отвори со подготвена порака. Таа ќе биде испратена дури откако сами ќе ја испратите.", "Nëse na kontaktoni përmes lidhjes WhatsApp, WhatsApp hapet me një mesazh të përgatitur. Mesazhi dërgohet vetëm pasi ta nisni vetë."],
    ["Bitte beachten Sie, dass bei der Nutzung von WhatsApp Daten an WhatsApp bzw. Meta Platforms verarbeitet werden können. Anbieter ist, soweit in Europa relevant, Meta Platforms Ireland Ltd., Merrion Road, Dublin 4, D04 X2K5, Irland. Dabei kann eine Verarbeitung oder Übermittlung in Drittländer, insbesondere in die USA, nicht ausgeschlossen werden. Für die Verarbeitung innerhalb von WhatsApp gelten zusätzlich die Datenschutzbedingungen von WhatsApp.", "Имајте предвид дека при користење WhatsApp, WhatsApp односно Meta Platforms може да обработува податоци. Релевантниот давател за Европа е Meta Platforms Ireland Ltd., Merrion Road, Dublin 4, D04 X2K5, Ирска. Не може да се исклучи обработка или пренос во трети земји, особено во САД. За обработката во WhatsApp дополнително важат правилата за приватност на WhatsApp.", "Ju lutemi vini re se përdorimi i WhatsApp mund të përfshijë përpunimin e të dhënave nga WhatsApp ose Meta Platforms. Ofruesi përkatës në Evropë është Meta Platforms Ireland Ltd., Merrion Road, Dublin 4, D04 X2K5, Irlandë. Nuk mund të përjashtohet përpunimi ose transferimi në vende të treta, veçanërisht në SHBA. Për përpunimin brenda WhatsApp vlejnë gjithashtu rregullat e privatësisë së WhatsApp."],
    ["Die Daten werden verarbeitet, um Ihre Anfrage zu beantworten, ein Angebot zu erstellen, Rückfragen zu klären und gegebenenfalls einen Montagetermin zu vereinbaren. Rechtsgrundlage ist Art. 6 Abs. 1 lit. b DSGVO, soweit die Verarbeitung zur Durchführung vorvertraglicher Maßnahmen oder eines Vertrags erforderlich ist. In anderen Fällen erfolgt die Verarbeitung auf Grundlage unseres berechtigten Interesses an der Bearbeitung von Kundenanfragen gemäß Art. 6 Abs. 1 lit. f DSGVO.", "Податоците се обработуваат за да одговориме на вашето барање, да изготвиме понуда, да разјасниме дополнителни прашања и, доколку е потребно, да договориме термин за монтажа. Правната основа е чл. 6 став 1 точка б од GDPR, кога обработката е потребна за преддоговорни мерки или договор. Во другите случаи, обработката се заснова на нашиот легитимен интерес за одговор на барањата на клиентите согласно чл. 6 став 1 точка ѓ од GDPR.", "Të dhënat përpunohen për t'iu përgjigjur kërkesës suaj, për të përgatitur një ofertë, për të sqaruar pyetje dhe, nëse nevojitet, për të caktuar montimin. Baza ligjore është neni 6, paragrafi 1, pika b e GDPR-së kur përpunimi nevojitet për masa para-kontraktore ose për zbatimin e një kontrate. Në raste të tjera, përpunimi bazohet në interesin tonë legjitim për trajtimin e kërkesave të klientëve sipas nenit 6, paragrafi 1, pika f të GDPR-së."],
    ["Die Bereitstellung Ihrer Daten ist nicht gesetzlich vorgeschrieben. Ohne die erforderlichen Kontaktdaten und Angaben zur Anfrage können wir Ihre Anfrage jedoch nicht oder nur eingeschränkt bearbeiten.", "Доставувањето на податоците не е законски задолжително. Сепак, без потребните контакт-податоци и информации за барањето, не можеме целосно да го обработиме.", "Dhënia e të dhënave nuk kërkohet me ligj. Megjithatë, pa të dhënat e nevojshme të kontaktit dhe informacionet e kërkesës, nuk mund ta trajtojmë kërkesën tuaj ose mund ta trajtojmë vetëm pjesërisht."],
    ["Wir speichern Ihre Daten nur so lange, wie es für die Bearbeitung Ihrer Anfrage, die Angebotserstellung und gesetzliche Aufbewahrungspflichten erforderlich ist. Wenn kein Auftrag zustande kommt und keine gesetzlichen Pflichten entgegenstehen, werden die Daten gelöscht, sobald sie für den Zweck nicht mehr erforderlich sind.", "Ги чуваме податоците само онолку долго колку што е потребно за обработка на барањето, подготовка на понудата и исполнување на законските обврски за чување. Ако не се склучи договор и нема законска обврска за чување, податоците се бришат штом веќе не се потребни.", "Të dhënat i ruajmë vetëm për aq kohë sa nevojitet për trajtimin e kërkesës, përgatitjen e ofertës dhe përmbushjen e detyrimeve ligjore të ruajtjes. Nëse nuk lidhet kontratë dhe nuk ka detyrim ligjor për ruajtje, të dhënat fshihen sapo të mos jenë më të nevojshme."],
    ["Eine Weitergabe Ihrer Daten an Dritte erfolgt nicht zu Werbezwecken und Ihre Daten werden nicht verkauft. Eine Weitergabe kann erfolgen, wenn dies zur Bearbeitung Ihrer Anfrage erforderlich ist, wenn gesetzliche Pflichten bestehen oder wenn Sie ausdrücklich eingewilligt haben.", "Вашите податоци не им се предаваат на трети страни за рекламирање и не се продаваат. Може да бидат споделени кога е потребно за обработка на барањето, кога постои законска обврска или кога сте дале изречна согласност.", "Të dhënat tuaja nuk u kalohen palëve të treta për reklamim dhe nuk shiten. Ato mund të ndahen kur kjo nevojitet për trajtimin e kërkesës, kur ekziston detyrim ligjor ose kur keni dhënë pëlqimin tuaj të qartë."],
    ["Diese Website wird derzeit über GitHub Pages bereitgestellt. Anbieter ist GitHub, Inc., 88 Colin P. Kelly Jr. Street, San Francisco, CA 94107, USA. Beim Aufruf der Website können technisch notwendige Zugriffsdaten verarbeitet werden, zum Beispiel IP-Adresse, Datum und Uhrzeit des Zugriffs, Browsertyp, Betriebssystem, Referrer-URL und aufgerufene Dateien. Diese Daten dienen der sicheren und stabilen Bereitstellung der Website. Da GitHub ein Anbieter mit Sitz in den USA ist, kann eine Übermittlung personenbezogener Daten in die USA nicht ausgeschlossen werden.", "Оваа веб-страница моментално се хостира преку GitHub Pages. Давател е GitHub, Inc., 88 Colin P. Kelly Jr. Street, San Francisco, CA 94107, САД. При отворање може да се обработуваат технички потребни податоци, како IP-адреса, датум и време на пристап, тип на прелистувач, оперативен систем, URL на претходната страница и отворени датотеки. Овие податоци служат за безбедно и стабилно прикажување на веб-страницата. Бидејќи GitHub е со седиште во САД, не може да се исклучи пренос на лични податоци во САД.", "Kjo faqe aktualisht ofrohet përmes GitHub Pages. Ofruesi është GitHub, Inc., 88 Colin P. Kelly Jr. Street, San Francisco, CA 94107, SHBA. Gjatë hapjes mund të përpunohen të dhëna teknike të nevojshme, si adresa IP, data dhe ora e qasjes, lloji i shfletuesit, sistemi operativ, URL-ja e referuesit dhe skedarët e hapur. Këto të dhëna shërbejnë për ofrimin e sigurt dhe të qëndrueshëm të faqes. Meqë GitHub ndodhet në SHBA, nuk mund të përjashtohet transferimi i të dhënave personale atje."],
    ["Diese Website lädt Schriftarten von Google Fonts (fonts.googleapis.com und fonts.gstatic.com). Beim Laden der Schriftarten wird eine Verbindung zu Google hergestellt; dabei können insbesondere Ihre IP-Adresse und technische Zugriffsdaten übermittelt werden. Die auf dieser Website gezeigten Projekt- und Produktbilder werden direkt von unserem Webserver bereitgestellt.", "Оваа веб-страница вчитува фонтови од Google Fonts (fonts.googleapis.com и fonts.gstatic.com). При вчитување се воспоставува врска со Google; може да се пренесат вашата IP-адреса и технички податоци за пристап. Фотографиите на проектите и производите се доставуваат директно од нашиот веб-сервер.", "Kjo faqe ngarkon shkronja nga Google Fonts (fonts.googleapis.com dhe fonts.gstatic.com). Gjatë ngarkimit krijohet lidhje me Google; mund të transmetohen adresa juaj IP dhe të dhëna teknike të qasjes. Fotografitë e projekteve dhe produkteve ofrohen drejtpërdrejt nga serveri ynë."],
    ["Die Daten werden verarbeitet, um Ihre Anfrage zu beantworten, ein Angebot zu erstellen, Rückfragen zu klären und gegebenenfalls einen Montagetermin zu vereinbaren. Rechtsgrundlage ist Art. 6 Abs. 1 lit. b DSGVO, soweit die Verarbeitung zur Durchführung vorvertraglicher Maßnahmen oder eines Vertrags erforderlich ist. In anderen Fällen erfolgt die Verarbeitung auf Grundlage unseres berechtigten Interesses an der Bearbeitung von Kundenanfragen gemäß Art. 6 Abs. 1 lit. f DSGVO.", "Податоците се обработуваат за да одговориме на вашето барање, да изготвиме понуда, да разјасниме дополнителни прашања и, доколку е потребно, да договориме термин за монтажа. Правната основа е чл. 6 став 1 точка б од GDPR, кога обработката е потребна за преддоговорни мерки или договор. Во другите случаи, обработката се заснова на нашиот легитимен интерес за одговор на барањата на клиентите согласно чл. 6 став 1 точка ѓ од GDPR.", "Të dhënat përpunohen për t'iu përgjigjur kërkesës suaj, për të përgatitur një ofertë, për të sqaruar pyetje dhe, nëse nevojitet, për të caktuar montimin. Baza ligjore është neni 6, paragrafi 1, pika b e GDPR-së kur përpunimi nevojitet për masa para-kontraktore ose për zbatimin e një kontrate. Në raste të tjera, përpunimi bazohet në interesin tonë legjitim për trajtimin e kërkesave të klientëve sipas nenit 6, paragrafi 1, pika f të GDPR-së."],
    ["Die Bereitstellung Ihrer Daten ist nicht gesetzlich vorgeschrieben. Ohne die erforderlichen Kontaktdaten und Angaben zur Anfrage können wir Ihre Anfrage jedoch nicht oder nur eingeschränkt bearbeiten.", "Доставувањето на податоците не е законски задолжително. Сепак, без потребните контакт-податоци и информации за барањето, не можеме целосно да го обработиме.", "Dhënia e të dhënave nuk kërkohet me ligj. Megjithatë, pa të dhënat e nevojshme të kontaktit dhe informacionet e kërkesës, nuk mund ta trajtojmë kërkesën tuaj ose mund ta trajtojmë vetëm pjesërisht."],
    ["Eine automatisierte Entscheidungsfindung einschließlich Profiling findet nicht statt.", "Не се врши автоматизирано донесување одлуки, вклучително и профилирање.", "Nuk kryhet vendimmarrje e automatizuar, përfshirë profilizimin."],
    ["Sie haben nach der DSGVO das Recht auf Auskunft, Berichtigung, Löschung, Einschränkung der Verarbeitung, Datenübertragbarkeit sowie das Recht, der Verarbeitung zu widersprechen. Wenn die Verarbeitung auf einer Einwilligung beruht, können Sie diese Einwilligung jederzeit mit Wirkung für die Zukunft widerrufen.", "Според GDPR имате право на пристап, исправка, бришење, ограничување на обработката, преносливост на податоците и приговор на обработката. Ако обработката се заснова на согласност, можете да ја повлечете во секое време со дејство за во иднина.", "Sipas GDPR-së, keni të drejtë për qasje, korrigjim, fshirje, kufizim të përpunimit, bartje të të dhënave dhe kundërshtim të përpunimit. Nëse përpunimi bazohet në pëlqim, mund ta tërhiqni atë në çdo kohë për të ardhmen."],
    ["Sie haben das Recht, sich bei einer Datenschutzaufsichtsbehörde zu beschweren, wenn Sie der Ansicht sind, dass die Verarbeitung Ihrer personenbezogenen Daten gegen die DSGVO verstößt. Zuständig für private Unternehmen in Bayern ist in der Regel das Bayerische Landesamt für Datenschutzaufsicht, Promenade 18, 91522 Ansbach, Deutschland,", "Имате право да поднесете жалба до надзорен орган за заштита на податоци ако сметате дека обработката на вашите лични податоци ја прекршува GDPR. За приватни компании во Баварија надлежен е вообичаено Баварскиот државен орган за надзор на заштитата на податоци, Promenade 18, 91522 Ansbach, Германија,", "Keni të drejtë të paraqisni ankesë pranë autoritetit mbikëqyrës për mbrojtjen e të dhënave nëse mendoni se përpunimi i të dhënave tuaja personale shkel GDPR-në. Për bizneset private në Bavari zakonisht përgjegjës është Autoriteti Bavarez për Mbikëqyrjen e Mbrojtjes së të Dhënave, Promenade 18, 91522 Ansbach, Gjermani,"],
    ["Diese Datenschutzerklärung kann angepasst werden, wenn sich die Website, die eingesetzten Dienste oder die rechtlichen Anforderungen ändern.", "Оваа политика за приватност може да се измени ако се променат веб-страницата, користените услуги или законските барања.", "Kjo deklaratë privatësie mund të ndryshohet nëse ndryshojnë faqja, shërbimet e përdorura ose kërkesat ligjore."],
    ["Deutschland", "Германија", "Gjermani"], ["Inhaber:", "Сопственик:", "Pronari:"], ["Telefon:", "Телефон:", "Telefoni:"], ["E-Mail:", "Е-пошта:", "Email:"], ["Steuernummer:", "Даночен број:", "Numri tatimor:"],
    ["Umsatzsteuer: Kleinunternehmer gemäß § 19 UStG", "ДДВ: мал претприемач според § 19 UStG", "TVSH: biznes i vogël sipas § 19 UStG"], ["USt-IdNr.: Nicht vorhanden", "Идентификациски број за ДДВ: нема", "Nr. i TVSH-së: nuk ka"], ["Diese Website lädt Schriftarten von Google Fonts (fonts.googleapis.com und fonts.gstatic.com).", "Оваа веб-страница вчитува фонтови од Google Fonts.", "Kjo faqe ngarkon shkronja nga Google Fonts."],
    ["Kostenloses Angebot innerhalb von", "Бесплатна понуда во рок од", "Ofertë falas brenda"], ["8 Stunden.", "8 часа.", "8 orësh."], ["8 Stunden", "8 часа", "8 orësh"],
    ["Von der Anfrage bis zur professionellen Montage – alles aus einer Hand.", "Од барањето до професионалната монтажа – сè на едно место.", "Nga kërkesa deri te montimi profesional – gjithçka në një vend."], ["Unsere Leistungen", "Нашите услуги", "Shërbimet tona"], ["Schreiben Sie uns per WhatsApp oder senden Sie uns eine E-Mail –", "Пишете ни на WhatsApp или испратете ни е-пошта –", "Na shkruani në WhatsApp ose na dërgoni email –"], ["wir kontaktieren Sie schnellstmöglich.", "ќе ве контактираме што е можно побрзо.", "do t'ju kontaktojmë sa më shpejt."],
    ["Von der Beratung bis zur Montage", "Од советување до монтажа", "Nga këshillimi deri te montimi"], ["03 / MONTAGE & SERVICE", "03 / МОНТАЖА И СЕРВИС", "03 / MONTIM DHE SHËRBIM"], ["Das ganze Projekt.", "Целиот проект.", "I gjithë projekti."], ["In guten Händen.", "Во сигурни раце.", "Në duar të sigurta."], ["Fenster & Türen nach Ihren Anforderungen. Wir beraten Sie bei der Auswahl und bieten passende Lösungen inklusive professioneller Montage.", "Прозорци и врати според вашите потреби. Ве советуваме при изборот и нудиме соодветни решенија со професионална монтажа.", "Dritare dhe dyer sipas kërkesave tuaja. Ju këshillojmë në zgjedhje dhe ofrojmë zgjidhje të përshtatshme me montim profesional."],
    ["Anfrage senden", "Испратете барање", "Dërgoni kërkesë"], ["Per WhatsApp, E-Mail oder telefonisch.", "Преку WhatsApp, е-пошта или телефон.", "Me WhatsApp, email ose telefon."], ["Das ganze Projekt.", "Целиот проект.", "I gjithë projekti."], ["Präzise Arbeitsschritte", "Прецизни работни чекори", "Hapa pune të saktë"],
    ["Großzügige Glasflächen", "Големи стаклени површини", "Sipërfaqe të mëdha xhami"], ["Schiebetür in Anthrazit", "Лизгачка врата во антрацит", "Derë rrëshqitëse antracit"], ["Balkonfront mit Rollläden", "Балконска фронта со ролетни", "Ballkon me grila"], ["Schiebefenster", "Лизгачки прозорец", "Dritare rrëshqitëse"], ["Beschattung am Gebäude", "Засенчување на објектот", "Mbrojtje nga dielli në fasadë"], ["Vorbereitung am Fenster", "Подготовка на прозорецот", "Përgatitja e dritares"], ["Fenster mit Rollladen", "Прозорец со ролетна", "Dritare me grilë"], ["Arbeit am Fensterrahmen", "Работа на прозорската рамка", "Punë në kornizën e dritares"], ["Fensterfront im Innenraum", "Прозорска фронта во ентериер", "Fasadë me dritare në ambient të brendshëm"], ["Heller Eingangsbereich", "Светол влезен простор", "Hyrje e ndriçuar"], ["Klare Linien am Eingang", "Чисти линии на влезот", "Vija të pastra në hyrje"], ["Anthrazit und Holzoptik", "Антрацит и изглед на дрво", "Antracit dhe pamje druri"], ["Licht unterm Dach", "Светлина под покривот", "Dritë nën çati"], ["Frische Luft und Tageslicht", "Свеж воздух и дневна светлина", "Ajër i freskët dhe dritë natyrale"], ["Dachfenster im Ziegeldach", "Кровен прозорец на покрив од ќерамиди", "Dritare çatie në çati me tjegulla"], ["Innenansicht mit Sonnenschutz", "Внатрешен поглед со заштита од сонце", "Pamje e brendshme me mbrojtje nga dielli"], ["Außenliegende Beschattung", "Надворешно засенчување", "Mbrojtje e jashtme nga dielli"], ["Beschattung am Wohnbereich", "Засенчување на дневниот простор", "Mbrojtje nga dielli në ambientin e ndenjjes"], ["Rollladen am Fenster", "Ролетна на прозорец", "Grilë në dritare"],
    ["Fenster · Türen · Baufertigteile · Hausmeisterservice", "Прозорци · врати · градежни елементи · одржување на објекти", "Dritare · dyer · elemente ndërtimi · mirëmbajtje objektesh"], ["Telefonnummer ergänzen", "Додадете телефонски број", "Shtoni numrin e telefonit"], ["Nachricht", "Порака", "Mesazhi"], ["Nachricht:", "Порака:", "Mesazhi:"], ["Fotos zum Anhängen", "Фотографии за прикачување", "Fotografitë për bashkëngjitje"], ["keine", "нема", "asnjë"], ["Anfrage für ein kostenloses Angebot", "Барање за бесплатна понуда", "Kërkesë për ofertë falas"], ["Ihr Wohnort", "Вашето место", "Vendbanimi juaj"],
    ["Nach oben ↑︎", "На врвот ↑︎", "Në krye ↑︎"], ["PROHAUS Fenster & Türen", "PROHAUS прозорци и врати", "PROHAUS dritare dhe dyer"], ["PROHAUS Monteure bauen Fenster in einem Neubau ein", "Монтери на PROHAUS монтираат прозорци во нов објект", "Montuesit e PROHAUS instalojnë dritare në një ndërtesë të re"], ["Anthrazitfarbenes Schiebefenster", "Лизгачки прозорец во антрацит", "Dritare rrëshqitëse antracit"], ["Moderne Rollläden an Fenstern und Terrassentüren", "Модерни ролетни на прозорци и балконски врати", "Grila moderne në dritare dhe dyer tarrace"], ["Monteur arbeitet an einem Fensterrahmen", "Монтер работи на прозорска рамка", "Montuesi punon në kornizën e dritares"],
    ["Große Fensterfront mit mehreren Türen auf einem Balkon", "Голема прозорска фронта со повеќе врати на балкон", "Fasadë e madhe me dritare dhe disa dyer në ballkon"], ["Anthrazitfarbene Schiebetür", "Лизгачка врата во антрацит", "Derë rrëshqitëse antracit"], ["Verglaste Balkonfront mit Beschattung", "Застаклена балконска фронта со засенчување", "Ballkon me xham dhe mbrojtje nga dielli"], ["Modernes anthrazitfarbenes Schiebefenster", "Модерен лизгачки прозорец во антрацит", "Dritare moderne rrëshqitëse antracit"], ["Fassade mit Fenstern und Rollläden", "Фасада со прозорци и ролетни", "Fasadë me dritare dhe grila"], ["Fensteröffnung während der Montage", "Отвор за прозорец за време на монтажата", "Hapësira e dritares gjatë montimit"], ["Fenster mit integriertem Rollladen", "Прозорец со вградена ролетна", "Dritare me grilë të integruar"], ["Fenstermontage an der Außenfassade", "Монтажа на прозорец на надворешна фасада", "Montim dritareje në fasadën e jashtme"], ["Montageschritte beim Einbau eines Fensters", "Чекори при монтажа на прозорец", "Hapat e montimit të një dritareje"], ["Hohe Fenster und Terrassentür im Innenraum", "Високи прозорци и балконска врата во ентериер", "Dritare të larta dhe derë tarrace në ambient të brendshëm"], ["Helle Hauseingangstür mit Glaselementen", "Светла влезна врата со стаклени елементи", "Derë hyrëse e çelët me elemente xhami"], ["Moderne anthrazitfarbene Haustür", "Модерна влезна врата во антрацит", "Derë hyrëse moderne antracit"], ["Moderne Haustür in Anthrazit und Holzoptik", "Модерна влезна врата во антрацит и изглед на дрво", "Derë hyrëse moderne antracit me pamje druri"], ["Schnittdarstellung eines mehrkammerigen Fensterprofils", "Пресек на повеќекоморен прозорски профил", "Prerje e profilit të dritares me shumë dhoma"], ["Weitere Ansicht eines Fensterprofil-Querschnitts", "Дополнителен приказ на пресек на прозорски профил", "Pamje tjetër e prerjes së profilit të dritares"], ["Zwei Dachfenster in einem dunklen Ziegeldach", "Два кровни прозорци на темен покрив од ќерамиди", "Dy dritare çatie në një çati të errët me tjegulla"], ["Offenes Dachfenster in einem Ziegeldach", "Отворен кровен прозорец на покрив од ќерамиди", "Dritare çatie e hapur në çati me tjegulla"], ["Geöffnetes Dachfenster auf einem Terrakottadach", "Отворен кровен прозорец на покрив од теракота", "Dritare çatie e hapur në çati terrakote"], ["Dachfenster mit Innenrollo in einem hellen Raum", "Кровен прозорец со внатрешна ролетна во светла соба", "Dritare çatie me grilë të brendshme në dhomë të ndriçuar"], ["Moderne Rollläden an einer beleuchteten Hausfassade", "Модерни ролетни на осветлена фасада", "Grila moderne në fasadë të ndriçuar"], ["Terrassentüren und Fenster mit Rollläden", "Балконски врати и прозорци со ролетни", "Dyer tarrace dhe dritare me grila"], ["Rollladen an der Außenwand eines Hauses", "Ролетна на надворешен ѕид на куќа", "Grilë në murin e jashtëm të shtëpisë"]
  ];

  const dictionary = { mk: new Map(), sq: new Map() };
  rows.forEach(([de, mk, sq]) => { dictionary.mk.set(de, mk); dictionary.sq.set(de, sq); });
  const whatsappMessages = {
    de: "Hallo PROHAUS, ich interessiere mich für ein kostenloses Angebot.",
    mk: "Здраво PROHAUS, заинтересиран/а сум за бесплатна понуда.",
    sq: "Përshëndetje PROHAUS, jam i/e interesuar për një ofertë falas."
  };
  const languageNames = { de: "Deutsch", mk: "Македонски", sq: "Shqip" };
  const originals = new WeakMap();
  const originalAttributes = new WeakMap();
  let language = "de";
  try { language = localStorage.getItem("prohaus-language") || "de"; } catch {}
  if (!dictionary[language] && language !== "de") language = "de";

  const translateText = value => dictionary[language]?.get(value) || value;
  const applyLanguage = next => {
    language = next;
    if (language !== "de" && !dictionary[language]) language = "de";
    try { localStorage.setItem("prohaus-language", language); } catch {}
    document.documentElement.lang = language;
    const title = document.querySelector("title");
    if (title) {
      if (!originals.has(title)) originals.set(title, title.textContent);
      title.textContent = translateText(originals.get(title));
    }
    const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT);
    while (walker.nextNode()) {
      const node = walker.currentNode;
      const initial = originals.has(node) ? originals.get(node) : node.nodeValue;
      originals.set(node, initial);
      const trimmed = initial.trim();
      if (!trimmed) continue;
      const translated = translateText(trimmed);
      const leading = initial.match(/^\s*/)?.[0] || "";
      const trailing = initial.match(/\s*$/)?.[0] || "";
      node.nodeValue = leading + translated + trailing;
    }
    document.querySelectorAll("[placeholder], [aria-label], img[alt], meta[name='description']").forEach(element => {
      const attributes = element.matches("meta[name='description']") ? ["content"] : ["placeholder", "aria-label", "alt"];
      attributes.forEach(attribute => {
        if (!element.hasAttribute(attribute)) return;
        let saved = originalAttributes.get(element);
        if (!saved) { saved = {}; originalAttributes.set(element, saved); }
        if (!(attribute in saved)) saved[attribute] = element.getAttribute(attribute);
        element.setAttribute(attribute, translateText(saved[attribute]));
      });
    });
    document.querySelectorAll(".language-select").forEach(select => { select.value = language; });
    document.querySelectorAll('a[href^="https://wa.me/"]').forEach(link => {
      const url = new URL(link.href);
      url.searchParams.set("text", whatsappMessages[language]);
      link.href = url.toString();
    });
  };

  document.querySelectorAll(".language-select").forEach(select => select.addEventListener("change", () => applyLanguage(select.value)));
  window.PROHAUS_I18N = { get language() { return language; }, t: translateText, names: languageNames };
  applyLanguage(language);
})();
